version: '2.1'
services:
  db:
    hostname: db.magento2.docker
    image: 'mariadb:10.2'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '3306:3306'
    volumes:
      - ./var/docker/mariadb/db:/var/lib/mysql:cached
    healthcheck:
      test: 'mysqladmin ping -h localhost'
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    hostname: redis.magento2.docker
    image: 'redis:5.0'
    ports:
      - '6379:6379'
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
  elasticsearch:
    hostname: elasticsearch.magento2.docker
    image: 'magento/magento-cloud-docker-elasticsearch:6.5-1.1'
    ports:
      - '9200:9200'
  mailhog:
    hostname: mailhog.magento2.docker
    image: 'mailhog/mailhog:latest'
    restart: always
    command: ['-storage=maildir', '-maildir-path=/home/mailhog/maildir']
    ports:
      - '1025:1025'
      - '8025:8025'
